#############################################################################
# Makefile for building: Wholesale_Club_Project.app/Contents/MacOS/Wholesale_Club_Project
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  Wholesale_Club_Project.pro
# Template: app
# Command: /Users/Jason/Qt/5.7/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile Wholesale_Club_Project.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I../../../Qt/5.7/clang_64/lib/QtGui.framework/Headers -I../../../Qt/5.7/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../../Qt/5.7/clang_64/mkspecs/macx-clang -F/Users/Jason/Qt/5.7/clang_64/lib
QMAKE         = /Users/Jason/Qt/5.7/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Wholesale_Club_Project1.0.0
DISTDIR = /Users/Jason/Desktop/Wholesale/Wholesale-Club-master/.tmp/Wholesale_Club_Project1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 -Wl,-rpath,/Users/Jason/Qt/5.7/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/Jason/Qt/5.7/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		memberlist.cpp \
		date.cpp \
		itemlist.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		memberlist.o \
		date.o \
		itemlist.o \
		moc_mainwindow.o
DIST          = shoppers.txt \
		../../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/lex.prf \
		Wholesale_Club_Project.pro mainwindow.h \
		linkedlist.h \
		memberlist.h \
		date.h \
		itemlist.h main.cpp \
		mainwindow.cpp \
		memberlist.cpp \
		date.cpp \
		itemlist.cpp
QMAKE_TARGET  = Wholesale_Club_Project
DESTDIR       = 
TARGET        = Wholesale_Club_Project.app/Contents/MacOS/Wholesale_Club_Project


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d Wholesale_Club_Project.app/Contents/MacOS/ || mkdir -p Wholesale_Club_Project.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Wholesale_Club_Project.pro ../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.7/clang_64/mkspecs/features/lex.prf \
		Wholesale_Club_Project.pro \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../../Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile Wholesale_Club_Project.pro
../../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.7/clang_64/mkspecs/qdevice.pri:
../../../Qt/5.7/clang_64/mkspecs/features/device_config.prf:
../../../Qt/5.7/clang_64/mkspecs/common/unix.conf:
../../../Qt/5.7/clang_64/mkspecs/common/mac.conf:
../../../Qt/5.7/clang_64/mkspecs/common/macx.conf:
../../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf:
../../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt/5.7/clang_64/mkspecs/common/clang.conf:
../../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt/5.7/clang_64/mkspecs/qconfig.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf:
../../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf:
../../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.7/clang_64/mkspecs/features/default_post.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt/5.7/clang_64/mkspecs/features/qml_debug.prf:
../../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf:
../../../Qt/5.7/clang_64/mkspecs/features/qt.prf:
../../../Qt/5.7/clang_64/mkspecs/features/resources.prf:
../../../Qt/5.7/clang_64/mkspecs/features/moc.prf:
../../../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.7/clang_64/mkspecs/features/uic.prf:
../../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf:
../../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf:
../../../Qt/5.7/clang_64/mkspecs/features/yacc.prf:
../../../Qt/5.7/clang_64/mkspecs/features/lex.prf:
Wholesale_Club_Project.pro:
../../../Qt/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../../Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl:
../../../Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile Wholesale_Club_Project.pro

qmake_all: FORCE

Wholesale_Club_Project.app/Contents/PkgInfo: 
	@test -d Wholesale_Club_Project.app/Contents || mkdir -p Wholesale_Club_Project.app/Contents
	@$(DEL_FILE) Wholesale_Club_Project.app/Contents/PkgInfo
	@echo "APPL????" > Wholesale_Club_Project.app/Contents/PkgInfo
Wholesale_Club_Project.app/Contents/Resources/empty.lproj: 
	@test -d Wholesale_Club_Project.app/Contents/Resources || mkdir -p Wholesale_Club_Project.app/Contents/Resources
	@touch Wholesale_Club_Project.app/Contents/Resources/empty.lproj
	
Wholesale_Club_Project.app/Contents/Info.plist: 
	@test -d Wholesale_Club_Project.app/Contents || mkdir -p Wholesale_Club_Project.app/Contents
	@$(DEL_FILE) Wholesale_Club_Project.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,jason.Wholesale-Club-Project,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,Wholesale_Club_Project,g" -e "s,@LIBRARY@,Wholesale_Club_Project,g" -e "s,@TYPEINFO@,????,g" ../../../Qt/5.7/clang_64/mkspecs/macx-clang/Info.plist.app >Wholesale_Club_Project.app/Contents/Info.plist

all: Makefile \
		Wholesale_Club_Project.app/Contents/PkgInfo \
		Wholesale_Club_Project.app/Contents/Resources/empty.lproj \
		Wholesale_Club_Project.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h linkedlist.h memberlist.h date.h itemlist.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp memberlist.cpp date.cpp itemlist.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Wholesale_Club_Project.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: ../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		memberlist.h \
		linkedlist.h \
		date.h \
		itemlist.h \
		mainwindow.h \
		../../../Qt/5.7/clang_64/bin/moc
	/Users/Jason/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/Jason/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/Jason/Desktop/Wholesale/Wholesale-Club-master -I/Users/Jason/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/Jason/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/Jason/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/usr/local/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/usr/include -I'/System/Library/Frameworks (framework directory)' -I'/Library/Frameworks (framework directory)' -F/Users/Jason/Qt/5.7/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../../../Qt/5.7/clang_64/bin/uic
	/Users/Jason/Qt/5.7/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		memberlist.h \
		linkedlist.h \
		date.h \
		itemlist.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		memberlist.h \
		linkedlist.h \
		date.h \
		itemlist.h \
		ui_mainwindow.h \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

memberlist.o: memberlist.cpp memberlist.h \
		linkedlist.h \
		date.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o memberlist.o memberlist.cpp

date.o: date.cpp date.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o date.o date.cpp

itemlist.o: itemlist.cpp itemlist.h \
		linkedlist.h \
		date.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o itemlist.o itemlist.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

