#############################################################################
# Makefile for building: Wholesale_Club_Project
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  Wholesale_Club_Project.pro
# Template: app
# Command: E:\QtCreator\5.5\mingw492_32\bin\qmake.exe -spec win32-g++ -o Makefile Wholesale_Club_Project.pro
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = E:\QtCreator\5.5\mingw492_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: Wholesale_Club_Project.pro E:/QtCreator/5.5/mingw492_32/mkspecs/win32-g++/qmake.conf E:/QtCreator/5.5/mingw492_32/mkspecs/features/spec_pre.prf \
		E:/QtCreator/5.5/mingw492_32/mkspecs/qdevice.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/features/device_config.prf \
		E:/QtCreator/5.5/mingw492_32/mkspecs/qconfig.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_3dcollision.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_3dcollision_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_3dcore.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_3dcore_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_3dinput.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_3dinput_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_3dlogic.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_3dlogic_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquick.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquick_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_3drenderer.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_3drenderer_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_axbase.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_axbase_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_axcontainer.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_axserver.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_axserver_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_bluetooth.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_clucene_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_concurrent.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_core.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_core_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_dbus.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_dbus_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_declarative.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_declarative_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_designer.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_designer_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_enginio.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_enginio_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_gui.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_gui_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_help.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_help_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_location.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_location_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_multimedia.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_network.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_network_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_nfc.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_nfc_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_opengl.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_opengl_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_openglextensions.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_platformsupport_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_positioning.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_positioning_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_printsupport.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_qml.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_qml_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_qmltest.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_quick.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_quick_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_script.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_script_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_scripttools.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_sensors.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_sensors_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_serialport.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_serialport_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_sql.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_sql_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_svg.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_svg_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_testlib.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_testlib_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_uiplugin.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_uitools.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_uitools_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_webchannel.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_webkit.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_webkit_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_webkitwidgets.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_websockets.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_websockets_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_widgets.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_widgets_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_winextras.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_winextras_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_xml.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_xml_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		E:/QtCreator/5.5/mingw492_32/mkspecs/features/qt_functions.prf \
		E:/QtCreator/5.5/mingw492_32/mkspecs/features/qt_config.prf \
		E:/QtCreator/5.5/mingw492_32/mkspecs/features/win32/qt_config.prf \
		E:/QtCreator/5.5/mingw492_32/mkspecs/win32-g++/qmake.conf \
		E:/QtCreator/5.5/mingw492_32/mkspecs/features/spec_post.prf \
		E:/QtCreator/5.5/mingw492_32/mkspecs/features/exclusive_builds.prf \
		E:/QtCreator/5.5/mingw492_32/mkspecs/features/default_pre.prf \
		E:/QtCreator/5.5/mingw492_32/mkspecs/features/win32/default_pre.prf \
		E:/QtCreator/5.5/mingw492_32/mkspecs/features/resolve_config.prf \
		E:/QtCreator/5.5/mingw492_32/mkspecs/features/exclusive_builds_post.prf \
		E:/QtCreator/5.5/mingw492_32/mkspecs/features/default_post.prf \
		E:/QtCreator/5.5/mingw492_32/mkspecs/features/c++11.prf \
		E:/QtCreator/5.5/mingw492_32/mkspecs/features/win32/rtti.prf \
		E:/QtCreator/5.5/mingw492_32/mkspecs/features/precompile_header.prf \
		E:/QtCreator/5.5/mingw492_32/mkspecs/features/warn_on.prf \
		E:/QtCreator/5.5/mingw492_32/mkspecs/features/qt.prf \
		E:/QtCreator/5.5/mingw492_32/mkspecs/features/resources.prf \
		E:/QtCreator/5.5/mingw492_32/mkspecs/features/moc.prf \
		E:/QtCreator/5.5/mingw492_32/mkspecs/features/win32/opengl.prf \
		E:/QtCreator/5.5/mingw492_32/mkspecs/features/uic.prf \
		E:/QtCreator/5.5/mingw492_32/mkspecs/features/win32/windows.prf \
		E:/QtCreator/5.5/mingw492_32/mkspecs/features/testcase_targets.prf \
		E:/QtCreator/5.5/mingw492_32/mkspecs/features/exceptions.prf \
		E:/QtCreator/5.5/mingw492_32/mkspecs/features/yacc.prf \
		E:/QtCreator/5.5/mingw492_32/mkspecs/features/lex.prf \
		Wholesale_Club_Project.pro \
		E:/QtCreator/5.5/mingw492_32/lib/qtmain.prl \
		E:/QtCreator/5.5/mingw492_32/lib/Qt5Widgets.prl \
		E:/QtCreator/5.5/mingw492_32/lib/Qt5Gui.prl \
		E:/QtCreator/5.5/mingw492_32/lib/Qt5Core.prl
	$(QMAKE) -spec win32-g++ -o Makefile Wholesale_Club_Project.pro
E:/QtCreator/5.5/mingw492_32/mkspecs/features/spec_pre.prf:
E:/QtCreator/5.5/mingw492_32/mkspecs/qdevice.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/features/device_config.prf:
E:/QtCreator/5.5/mingw492_32/mkspecs/qconfig.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_3dcollision.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_3dcollision_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_3dcore.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_3dcore_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_3dinput.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_3dinput_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_3dlogic.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_3dlogic_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquick.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquick_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquickrenderer.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_3drenderer.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_3drenderer_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_axbase.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_axbase_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_axcontainer.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_axcontainer_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_axserver.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_axserver_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_bluetooth.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_bluetooth_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_bootstrap_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_clucene_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_concurrent.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_concurrent_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_core.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_core_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_dbus.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_dbus_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_declarative.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_declarative_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_designer.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_designer_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_designercomponents_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_enginio.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_enginio_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_gui.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_gui_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_help.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_help_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_location.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_location_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_multimedia.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_multimedia_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_network.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_network_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_nfc.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_nfc_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_opengl.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_opengl_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_openglextensions.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_openglextensions_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_platformsupport_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_positioning.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_positioning_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_printsupport.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_printsupport_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_qml.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_qml_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_qmldevtools_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_qmltest.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_qmltest_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_quick.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_quick_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_quickparticles_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_quickwidgets.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_quickwidgets_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_script.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_script_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_scripttools.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_scripttools_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_sensors.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_sensors_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_serialport.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_serialport_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_sql.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_sql_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_svg.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_svg_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_testlib.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_testlib_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_uiplugin.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_uitools.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_uitools_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_webchannel.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_webchannel_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_webkit.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_webkit_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_webkitwidgets.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_websockets.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_websockets_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_widgets.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_widgets_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_winextras.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_winextras_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_xml.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_xml_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
E:/QtCreator/5.5/mingw492_32/mkspecs/features/qt_functions.prf:
E:/QtCreator/5.5/mingw492_32/mkspecs/features/qt_config.prf:
E:/QtCreator/5.5/mingw492_32/mkspecs/features/win32/qt_config.prf:
E:/QtCreator/5.5/mingw492_32/mkspecs/win32-g++/qmake.conf:
E:/QtCreator/5.5/mingw492_32/mkspecs/features/spec_post.prf:
E:/QtCreator/5.5/mingw492_32/mkspecs/features/exclusive_builds.prf:
E:/QtCreator/5.5/mingw492_32/mkspecs/features/default_pre.prf:
E:/QtCreator/5.5/mingw492_32/mkspecs/features/win32/default_pre.prf:
E:/QtCreator/5.5/mingw492_32/mkspecs/features/resolve_config.prf:
E:/QtCreator/5.5/mingw492_32/mkspecs/features/exclusive_builds_post.prf:
E:/QtCreator/5.5/mingw492_32/mkspecs/features/default_post.prf:
E:/QtCreator/5.5/mingw492_32/mkspecs/features/c++11.prf:
E:/QtCreator/5.5/mingw492_32/mkspecs/features/win32/rtti.prf:
E:/QtCreator/5.5/mingw492_32/mkspecs/features/precompile_header.prf:
E:/QtCreator/5.5/mingw492_32/mkspecs/features/warn_on.prf:
E:/QtCreator/5.5/mingw492_32/mkspecs/features/qt.prf:
E:/QtCreator/5.5/mingw492_32/mkspecs/features/resources.prf:
E:/QtCreator/5.5/mingw492_32/mkspecs/features/moc.prf:
E:/QtCreator/5.5/mingw492_32/mkspecs/features/win32/opengl.prf:
E:/QtCreator/5.5/mingw492_32/mkspecs/features/uic.prf:
E:/QtCreator/5.5/mingw492_32/mkspecs/features/win32/windows.prf:
E:/QtCreator/5.5/mingw492_32/mkspecs/features/testcase_targets.prf:
E:/QtCreator/5.5/mingw492_32/mkspecs/features/exceptions.prf:
E:/QtCreator/5.5/mingw492_32/mkspecs/features/yacc.prf:
E:/QtCreator/5.5/mingw492_32/mkspecs/features/lex.prf:
Wholesale_Club_Project.pro:
E:/QtCreator/5.5/mingw492_32/lib/qtmain.prl:
E:/QtCreator/5.5/mingw492_32/lib/Qt5Widgets.prl:
E:/QtCreator/5.5/mingw492_32/lib/Qt5Gui.prl:
E:/QtCreator/5.5/mingw492_32/lib/Qt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec win32-g++ -o Makefile Wholesale_Club_Project.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
